package net.mugeemu.ms.enums;

/**
 * Created on 1/25/2018.
 */
public enum MessageType {
    DROP_PICKUP_MESSAGE(0),
    QUEST_RECORD_MESSAGE(1),
    QUEST_RECORD_MESSAGE_ADD_VALID_CHECK(1),
    CASH_ITEM_EXPIRE_MESSAGE(2),
    INC_EXP_MESSAGE(3),
    INC_SP_MESSAGE(4),
    INC_POP_MESSAGE(5),
    INC_MONEY_MESSAGE(6),
    INC_GP_MESSAGE(7),
    INC_COMMITMENT_MESSAGE(7),
    GIVE_BUFF_MESSAGE(8),
    GENERAL_ITEM_EXPIRE_MESSAGE(9),
    SYSTEM_MESSAGE(10),
    QUEST_RECORD_EX_MESSAGE(11),

    ITEM_PROTECT_EXPIRE_MESSAGE(13),
    SKILL_EXPIRE_MESSAGE(14),
    WORLD_SHARE_RECORD_MESSAGE(14),
    ITEM_EXPIRE_REPLACE_MESSAGE(14),
    ITEM_ABILITY_TIME_LIMITED_EXPIRE_MESSAGE(14),
    INC_HARDCORE_EXP_MESSAGE(14),
    STYLISH_KILL_MESSAGE(14),
    BARRIER_EFFECT_IGNORE_MESSAGE(14),
    INC_NON_COMBAT_STAT_EXP_MESSAGE(14),

    ;

    private byte val;

    MessageType(int val) {
        this.val = (byte) val;
    }

    public byte getVal() {
        return val;
    }
}
